### PR TITLE
Makefile: add `install` rule

### PR DESCRIPTION
**Pull request by dunn**

### CODE REVIEW

**Comment by gmarcais** [comment]
Thanks for the patch. Let me ask you a question. The man page is available with 'yaggo -m', which is non standard. Do you think that 'make install' should also install a proper man page in $(prefix)/share/man/man1?

**Comment by dunn** [comment]
That seems like a good idea, yeah!

**Comment by dunn** [comment]
I don't know if you'd like to remove the `yaggo -m` command to avoid updating two different man files, or if they can both be build from a single source.

**Comment by gmarcais** [comment]
The man page would be generated by `yaggo -m`. In some sense it is a waste of space: the page is saved twice. But it is often better to just do `man yaggo` and get something rather than an error.

**Comment by dunn** [comment]
How's this?

**Pull request merged**
